bag/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

products/urls.py
# Imports available urls paths and views
from django.urls import path
from . import views


# Create list with routes and list
# 'all_products' view function and 'products' variable from views.py
# requires registration in project wide router in project_main/urls.py
urlpatterns = [
    path('', views.all_products, name='products'),  # Route for catalog view
    # Route for detail view, specifying that id is an integer
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    # Route for custom product view
    path('custom/', views.add_custom_product, name='add_custom_product'),
    # Points to add product view
    path('add/', views.add_product, name='add_product'),
    # Edit product page
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    # Delete products at products/delete/product_id
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
]

project_main/urls.py
# Allauth requires 'include'
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # Imports from settings.py
from django.conf.urls.static import static  # Import links to static files


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), # Required by Allauth
    path('', include('home.urls')),  # Including home view routing
    path('products/', include('products.urls')),  # Including products/urls.py
    path('bag/', include('bag.urls')),  # Including bag/urls.py
    path('checkout/', include('checkout.urls')),  # Including checkout/urls.py
    path('profile/', include('profiles.urls')),  # Including profiles/urls.py
]

# Path to media folder
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid  # Generates order numbers
from django.db import models
from django.db.models import Sum  # Imports sum function from Django models
from django.conf import settings  # Imports settings module from django.conf
from django_countries.fields import CountryField  # Requires django-countries
from products.models import Product  # Import products
from profiles.models import UserProfile  # Import from profiles/models.py


class Order(models.Model):
    """ Data to handle all orders, creates checkout_order table in db """
    # Non editable order number use with uuid
    order_number = models.CharField(max_length=32, null=False, editable=False)
    # ForeignKey to UserProfile and using models.SET_NULL to keep order record
    # when users deletes profile, allows purchases by visitors without profile
    # Making orders by profiles accessible via user.profile.order with 'orders'
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
            null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    # Auto date field
    date = models.DateTimeField(auto_now_add=True)
    # Content to be calculated with methods below
    delivery_cost = models.DecimalField(max_digits=6,
            decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10,
            decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10,
            decimal_places=2, null=False, default=0)
    # Prevent order double entry by saving original shopping bag info
    original_bag = models.TextField(null=False, blank=False, default='')
    # Prevent order double entry by saving Stripe payment intent id
    stripe_pid = models.CharField(max_length=254,
            null=False, blank=False, default='')


    def _generate_order_number(self):
        """
        Generate random 32 character long and unique order number using UUID
        """
        return uuid.uuid4().hex.upper()


    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        # Calculate sum of all items using aggregate function, or set to zero
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))\
                ['lineitem_total__sum'] or 0
        # Calculate delivery cost based on values set in settings
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = \
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()


    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)


    def __str__(self):
        """ Return order number """
        return self.order_number


class OrderLineItem(models.Model):
    """
    Order line items to specify each item in the order
    Creates checkout_orderlineitem table in db
    """
    order = models.ForeignKey(Order, null=False,
            blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product, null=False,
            blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=20, null=True,
            blank=True)  # format A3 PRINT
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
            null=False, blank=False, editable=False)


    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total and update
        the order total by calculating subtotal for each product in the order
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)


    def __str__(self):
        """
        Return sku for each product in the order
        """
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
# Check access with auth login decorator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Product, Category, Type, Format  # Import products
from .forms import ProductForm  # Import product form
from profiles.models import UserProfile  # Import from profile model


def all_products(request):
    """
    Show all products in catalog view
    Applicable for sorting and search queries
    """
    # Get all categories
    categories = Category.objects.all()
    # Get all products
    products = Product.objects.all()
    # Set query to None
    query = None
    # For search queries, 'q' is the name of the query form set in base.html
    if request.GET:
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))
            queries = Q(name__icontains=query) | Q(
                description__icontains=query)
            products = products.filter(queries)

    # Making this data available in products.html
    context = {
        'products': products,
        'search_term': query,
        'categories': categories,
    }
    # Define in which file the 'context' will be rendered in
    # products/templates/products/products.html
    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ Show product detail view """
    # Get product by product_id
    product = get_object_or_404(Product, pk=product_id)
    context = {
        'product': product,
    }
    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a product to the store """
    # Limit user access, if not superuser
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))
    # If super user
    if request.method == 'POST':
        # Create instance of product form from post including files
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            # form.save()
            product = form.save()
            messages.success(request, 'Successfully added product!')
            # return redirect(reverse('add_product'))
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product.\
              Please ensure the form is valid.')
    else:
        # Render empty instance of the form with type and format set to none
        form = ProductForm(
            initial={
                'type': 0,
                'format': 0,
            }
        )
    # Template
    template = 'products/add_product.html'
    # Context for template
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def add_custom_product(request):
    """ Create custom product """
    if request.user.is_authenticated:
        # Get profile, username
        creator = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':
        # Get product form with values from post
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            # CALCULATE CUSTOM PRODUCT PRICE
            # Artwork price table
            def artwork(cost):
                dict = {
                    1: 160,
                    2: 120,
                    3: 80,
                }
                return dict.get(cost, 50)
            # Get form value from custom product 'type' field
            cost = int(form['type'].value())

            # Markup price table
            def markup(size):
                dict = {
                    1: 20,
                    2: 30,
                    3: 40,
                    4: 50,
                    5: 60,
                    6: 70,
                    7: 80,
                    8: 90,
                    9: 100,
                    10: 110,
                }
                return dict.get(size, 20)
            # Get form value from custom product 'format' field
            size = int(form['format'].value())
            # Calculate price based on type and format choice
            custom_product_price = artwork(cost) + markup(size)
            # Save current category value or index
            current_category = form['category'].value()
            # Update form value with calculated 'custom product' price
            # if current category is '1' (in the DB 1 = custom_product)
            if current_category == '1':
                form.instance.price = custom_product_price
            # form.save()
            product = form.save()
            messages.success(request, 'Successfully added custom artwork!')
            # return redirect(reverse('add_product'))
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product.\
              Please ensure the form is valid.')
    else:
        # Set initial category value to 'custom product' with db index '1'
        # Necessary for custom product creation and its pricing above
        # which is based on product category set to 'custom product'
        form = ProductForm(
            initial={
                'name': 'Custom Artwork',
                'category': 1,  # Set custom product index
                'created_by': creator,  # Sets username
                'price': 0.00,
                'rating': 0,
            }
        )
    # Template
    template = 'products/add_custom_product.html'
    # Context for template
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    # Get product
    product = get_object_or_404(Product, pk=product_id)
    # Allow non super users to edit 'custom product' when authenticated
    if request.user.is_authenticated and \
      str(product.category) == 'custom_product' or request.user.is_superuser:
        # If post
        if request.method == 'POST':
            # Make instance of product form with
            # request product and request files
            form = ProductForm(request.POST, request.FILES, instance=product)
            # If form valid
            if form.is_valid():
                # CALCULATE CUSTOM PRODUCT PRICE
                # Artwork price table
                def artwork(cost):
                    dict = {
                        1: 160,
                        2: 120,
                        3: 80,
                    }
                    return dict.get(cost, 50)
                # Get form value from custom product 'type' field
                cost = int(form['type'].value())

                # Markup price table
                def markup(size):
                    dict = {
                        1: 20,
                        2: 30,
                        3: 40,
                        4: 50,
                        5: 60,
                        6: 70,
                        7: 80,
                        8: 90,
                        9: 100,
                        10: 110,
                    }
                    return dict.get(size, 20)
                # Get form value from custom product 'format' field
                size = int(form['format'].value())
                # Calculate price based on type and format choice
                custom_product_price = artwork(cost) + markup(size)
                # Save current category value or index
                current_category = form['category'].value()
                # Update form value with calculated custom product price
                # if current category is '1'
                if current_category == '1':
                    form.instance.price = custom_product_price
                # Save
                form.save()
                # Response message
                messages.success(request, 'Successfully updated product!')
                # Redirect to product detail page with product id
                return redirect(reverse('product_detail', args=[product.id]))
            else:
                messages.error(request, 'Failed to update product.\
                  Please ensure the form is valid.')
        else:
            # Make instance of product form with produkt
            form = ProductForm(instance=product)
            messages.info(request, f'You are editing {product.name}')
        # Template to use
        template = 'products/edit_product.html'
        context = {
            'form': form,
            'product': product,
        }
        return render(request, template, context)
    else:
        # Limit user access
        if not request.user.is_superuser:
            messages.error(request, 'Sorry, only store owners can do that.')
            return redirect(reverse('home'))


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    # Get product
    product = get_object_or_404(Product, pk=product_id)
    # If product is 'custom product' allow logged in, non super users to delete
    if request.user.is_authenticated and \
      str(product.category) == 'custom_product' or request.user.is_superuser:
        # Call product delete
        product.delete()
        # Response message
        messages.success(request, 'Product deleted!')
        # Redirect to products view
        return redirect(reverse('products'))
    else:
        # Limit user access
        if not request.user.is_superuser:
            messages.error(request, 'Sorry, only store owners can do that.')
            return redirect(reverse('home'))

products/templates/products/add_custom_product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="uk-container uk-container-medium">
    <!-- Page title -->
    <h1 class="uk-heading-line uk-text-center uk-margin-medium-bottom">
      <span>Custom Artwork</span>
    </h1>
    <!-- Product cart -->
    <div class="uk-flex uk-flex-center uk-child-width-expand@s" uk-grid>
      <div class="uk-width-1-2@m">
        <div class="uk-card uk-card-default uk-card-body">
          <p>Custom Artwork Description</p>
          <!-- Form -->
          <form method="POST" action="{% url 'add_custom_product' %}" enctype="multipart/form-data" id="add_custom_product_form">
            <fieldset class="uk-fieldset">
              {% csrf_token %}
              <!-- User input fields -->
              <div class="uk-margin">
                {{ form.type|as_crispy_field }}
                {{ form.format|as_crispy_field }}
                {{ form.description|as_crispy_field }}
                {{ form.image|as_crispy_field }}
              </div>
              <!-- Required but hidden crispy fields -->
              <div class="uk-margin uk-hidden">
                {{ form.category|as_crispy_field }}
                {{ form.name|as_crispy_field }}
                {{ form.sku|as_crispy_field }}
                {{ form.price|as_crispy_field }}
                {{ form.created_by|as_crispy_field }}
                {{ form.rating|as_crispy_field }}
              </div>
              <p class="uk-text-small">Add a reference image.</p>
              <hr class="uk-margin">
              <div class="uk-text-right uk-margin-top">
                <a class="uk-button uk-button-default uk-border-pill" href="{% url 'products' %}">Cancel</a>
                <button class="uk-button uk-button-primary uk-border-pill" type="submit">Get Quote</button>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

<!-- Notifying the user of what the image will be changed to -->
{% block postloadjs %}
  {{ block.super }}
  <script>
    // Listen to change event on #new-image
    $('#new-image').change(function() {
      // Store new file in variable file
      var file = $('#new-image')[0].files[0];
      // Set file name paragraph in widget template to file name
      $('#filename').text(`Image will be set to: ${file.name}`);
    });
  </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <!-- Content wrappers -->
  <div class="uk-container uk-container-medium">
    <div class="uk-width-expand">
      <div class="uk-grid-small custom-product-flex" uk-grid>
        <!-- PRODUCT IMAGE -->
        <div class="uk-card custom-image-height">
          <div class="uk-card-media">
            {% if product.image %}
              <!-- uikit LIGHTBOX -->
              <div uk-lightbox="animate: fade">
                <a href="{{ product.image.url }}">
                  <img src="{{ product.image.url }}" 
                    width="500" 
                    alt="{{ product.name }}">
                </a>
              </div>
            {% else %}
              <img src="{{ MEDIA_URL }}noimage.png" 
                width="500" 
                alt="{{ product.name }}">
            {% endif %}
          </div>
        </div>
        <!-- PRODUCT INFO -->
        <div class="uk-card-body uk-margin-left uk-width-large">
          <div class="uk-text-left uk-text-large uk-text-bold uk-text-secondary uk-width-large">
            {{ product.name }}
          </div>
          <div class="uk-text-left uk-text-bold uk-margin-small-top">
            ${{ product.price }}
          </div>

          <!-- Show products if category is not custom product -->
          {% if product.category.name != 'custom_product' %}
            <div class="uk-text-left uk-text-small uk-text-secondary uk-margin-small-top">
              Category: {{ product.category.friendly_name }}
            </div>
          {% endif %}

          <!-- If 'custom product' show type and format of custom artwork -->
          {% if product.category.name == 'custom_product' %}
            <div class="uk-text-left uk-text-small uk-text-secondary uk-margin-small-top">
              <strong>Type:</strong> {{ product.type.friendly_name }}
            </div>
            <div class="uk-text-left uk-text-small uk-text-secondary uk-margin-small-top">
              <strong>Format:</strong> {{ product.format.friendly_name }}
            </div>
            <div class="uk-text-left uk-text-small uk-text-secondary uk-margin-small-top">
              <strong>Inquiry by:</strong> {{ product.created_by }}
            </div>
            <div class="uk-text-left uk-text-small uk-text-secondary uk-margin-small-top">
              {% if not product.image|length %}
                <p>A reference image helps to communicate the final outcome of a custom artwork.</p>
              {% endif %}
            </div>
          {% endif %}

          <!-- Rating or testimonials -->
          <div class="uk-grid-small uk-text-small" uk-grid>
            {% if product.rating %}
              <span class="uk-text-left uk-width-expand">
                <span class="uk-text-middle" uk-icon="icon: star; ratio: 0.8"></span>
                <span class="uk-text-middle"> {{ product.rating }} / 5</span>
              </span>
            {% endif %}
          </div>
          <!-- Product description -->
          <div class="uk-text-left uk-text-small uk-width-large uk-margin-small-top">
            {{ product.description }}
          </div>
          <!-- If admin - Product edit and delete -->
          {% if request.user.is_superuser %}
            <div class="uk-text-small uk-text-left uk-margin-small-top">
              <a href="{% url 'edit_product' product.id %}">Edit</a> | 
              <a class="uk-text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
            </div>
          {% else %}
            <!-- If product is 'custom product' -->
            {% if product.category.name == 'custom_product' %}
              <!-- And user is logged in -->
              {% if user.is_authenticated %}
                <div class="uk-text-small uk-text-left uk-margin-small-top">
                  <a href="{% url 'edit_product' product.id %}">Edit</a> | 
                  <a class="uk-text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                </div>
              {% endif %}
            {% endif %}
          {% endif %}
          <!-- ADD TO CART -->
          <div>
            <div class="uk-margin-medium-top" uk-margin>
              <form action="{% url 'add_to_bag' product.id %}" method="POST">
                <!-- Secure Django token -->
                {% csrf_token %}
                <!-- Size, format info -->
                {% with product.has_sizes as s %}
                  {% if s %}
                    <div class="uk-margin">
                      <select class="uk-select uk-form-small uk-form-width-medium"
                        name="product_size"
                        id="id_product_size">
                          <option value="A4 Print">Print Format A4</option>
                          <option value="A3 Print" selected>Print Format A3</option>
                          <option value="A2 Print">Print Format A2</option>
                      </select>
                    </div>
                  {% endif %}
                {% endwith %}
                <!-- Do not show quantity choice for custom products -->
                {% if product.category.name == 'custom_product' %}
                  <!-- Using uikit class uk-hidden to hide -->
                  <div class="uk-hidden">
                    <!-- Quantity field -->
                    <div class="uk-margin">
                      <div class="input-group uk-inline">
                        <!-- Minus button, requires js -->
                        <div class="intput-group">
                          <button class="decrement-qty uk-form-icon" 
                            data-item_id="{{ product.id }}" 
                            id="decrement-qty_{{ product.id }}"
                            uk-icon="icon: minus">
                          </button>
                        </div>
                        <!-- Plus button, requires js -->
                        <div class="intput-group">
                          <button class="increment-qty uk-form-icon uk-form-icon-flip" 
                            data-item_id="{{ product.id }}" 
                            id="increment-qty_{{ product.id }}"
                            uk-icon="icon: plus">
                          </button>
                        </div>
                        <!-- Input field -->
                        <input class="qty_input uk-input uk-form-small uk-form-width-small uk-text-center"
                          type="number"
                          name="quantity"
                          value="1"
                          min="1"
                          max="99"
                          data-item_id="{{ product.id }}"
                          id="id_qty_{{ product.id }}">
                      </div>
                    </div>
                  </div>
                {% else %}
                  <!-- Quantity field -->
                  <div class="uk-margin">
                    <div class="input-group uk-inline">
                      <!-- Minus button, requires js -->
                      <div class="intput-group">
                        <button class="decrement-qty uk-form-icon" 
                          data-item_id="{{ product.id }}" 
                          id="decrement-qty_{{ product.id }}"
                          uk-icon="icon: minus">
                        </button>
                      </div>
                      <!-- Plus button, requires js -->
                      <div class="intput-group">
                        <button class="increment-qty uk-form-icon uk-form-icon-flip" 
                          data-item_id="{{ product.id }}" 
                          id="increment-qty_{{ product.id }}"
                          uk-icon="icon: plus">
                        </button>
                      </div>
                      <!-- Input field -->
                      <input class="qty_input uk-input uk-form-small uk-form-width-small uk-text-center"
                        type="number"
                        name="quantity"
                        value="1"
                        min="1"
                        max="99"
                        data-item_id="{{ product.id }}"
                        id="id_qty_{{ product.id }}">
                    </div>
                  </div>
                {% endif %}
                <div>
                  <!-- Submit button -->
                  <button class="uk-button uk-button-secondary uk-border-pill"
                    type="submit">
                      Add to Bag
                  </button>
                  <!-- Redirection link to this page -->
                  <input type="hidden"
                    name="redirect_url"
                    value="{{ request.path }}">
                </div>
              </form>
              <!-- Link to custom product -->
              {% if product.category.name == 'custom_product' %}
                <div class="uk-hidden">
                  <a href="{% url 'add_custom_product' %}" class="uk-button uk-button-text uk-text-capitalize uk-margin-top">
                    Request custom artwork
                  </a>
                </div>
              {% else %}
                <hr class="uk-margin-medium-top uk-margin-remove-bottom">
                <a href="{% url 'add_custom_product' %}" class="uk-button uk-button-text uk-text-capitalize uk-margin-top">
                  Request custom artwork
                </a>
              {% endif %}
            </div>
          <!-- ADD TO CARD END -->
          </div>
        <!-- PRODUCT INFO END -->
        </div>
      <!-- END of content wrappers -->
      </div>
    </div>
  </div>
{% endblock %}

<!-- Including js file for quantity field with plus and minus dialer -->
{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}